In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris/Iris.csv
/kaggle/input/iris/database.sqlite


In [32]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

# Load the dataset
df = pd.read_csv('/kaggle/input/iris/Iris.csv')

# Convert the 'Species' column to numeric labels
df['Species'] = df['Species'].map({'Iris-setosa': 0, 'Iris-virginica': 1, 'Iris-versicolor': 2})

# Select features (ensure they are numeric)
X = df.iloc[:, 1:-1]  # Ensure all data is numeric
y = df.iloc[:, -1]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# KNN Classifier Class
class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X_train, y_train):
        self.X_train = X_train.values  # Convert to NumPy array
        self.y_train = y_train.values  # Convert to NumPy array

    def euclidean_distance(self, a, b):
        # Ensure a and b are numpy arrays for element-wise subtraction
        return np.sqrt(np.sum((a - b) ** 2, axis=1))

    def predict(self, X_test):
        predictions = []
        X_test = X_test.values  # Convert to NumPy array
        for test_point in X_test:
            # Calculate distances from the test point to all training points
            distances = self.euclidean_distance(self.X_train, test_point)

            # Get the indices of the k nearest neighbors
            k_indices = np.argsort(distances)[:self.k]

            # Get the labels of the k nearest neighbors
            k_labels = self.y_train[k_indices]

            # Majority voting: find the most frequent label manually
            unique_labels, counts = np.unique(k_labels, return_counts=True)
            majority_label = unique_labels[np.argmax(counts)]  # The label with the maximum count
            predictions.append(majority_label)

        return np.array(predictions)

# Instantiate the KNN classifier with k=3
knn = KNN(k=3)

# Train the KNN classifier
knn.fit(X_train, y_train)

# Predict on the test set
y_pred = knn.predict(X_test)

# Confusion Matrix and Accuracy
conf_matrix = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

# Print Results
print("True Labels:", y_test.values)  # Convert y_test to numpy array for printing
print("Predicted Labels:", y_pred)
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy:", accuracy)



True Labels: [2 0 1 2 2 0 2 1 2 2 1 0 0 0 0 2 1 2 2 1 0 1 0 1 1 1 1 1 0 0]
Predicted Labels: [2 0 1 2 2 0 2 1 2 2 1 0 0 0 0 2 1 2 2 1 0 1 0 1 1 1 1 1 0 0]
Confusion Matrix:
 [[10  0  0]
 [ 0 11  0]
 [ 0  0  9]]
Accuracy: 1.0
